typography_spectrum: 0.6491053618956357
color:
  brandColors:
    - '#000000'
    - '#0e76c3'
    - '#ff73ff'
    - '#49c0ff'
    - '#ffc65e'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5002488857135177
analytics:
  google: null
  facebook: null
  twitter: null
name: Technically Speaking
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Github
    url: 'https://github.com/Riice'
    type: external
favicon: null
title: Technically Speaking - Technology & Scripting from Reece
purpose: []
