name: Technically Speaking
favicon: null
layout_spectrum: 0.5002488857135177
typography_spectrum: 0.6491053618956357
title: Technically Speaking - Technology & Scripting from Reece
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0e76c3'
    - '#ff73ff'
    - '#49c0ff'
    - '#ffc65e'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
